from __future__ import annotations

from typing import Any

# Shared submenu entries (mirror satana.sh attack submenus).
_COMMON_INTERFACE_ITEMS: list[dict[str, Any]] = [
    {"number": "0", "title": "Вернуться в главное меню", "kind": "link", "href": "main_menu_page", "icon": "bi-arrow-left"},
    {"number": "1", "title": "Выбрать другой сетевой интерфейс", "kind": "link", "href": "interfaces_page", "icon": "bi-router"},
    {
        "number": "2",
        "title": "Перевести интерфейс в режим монитора",
        "kind": "action",
        "action": "monitor_mode",
        "icon": "bi-broadcast",
        "needs_interface": True,
    },
    {
        "number": "3",
        "title": "Перевести интерфейс в управляемый режим",
        "kind": "action",
        "action": "managed_mode",
        "icon": "bi-wifi",
        "needs_interface": True,
    },
]

_SCAN_ITEM = {
    "number": "4",
    "title": "Поиск целей (необходим режим монитора)",
    "kind": "action",
    "action": "scan_targets",
    "icon": "bi-radar",
    "needs_interface": True,
    "fields": [{"name": "seconds", "label": "Длительность сканирования (сек)", "type": "number", "default": "30"}],
}

MENUS: dict[str, dict[str, Any]] = {
    "dos_attacks": {
        "slug": "dos_attacks",
        "title": "Меню DoS атак",
        "parent_href": "main_menu_page",
        "items": [
            *_COMMON_INTERFACE_ITEMS,
            _SCAN_ITEM,
            {
                "number": "5",
                "title": "Атака деаутентификации / разъединения (mdk)",
                "kind": "action",
                "action": "mdk_deauth",
                "icon": "bi-lightning",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                    {"name": "pursuit", "label": "Режим преследования", "type": "checkbox"},
                ],
            },
            {
                "number": "6",
                "title": "Атака деаутентификации aireplay",
                "kind": "action",
                "action": "aireplay_deauth",
                "icon": "bi-lightning-charge",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                    {"name": "pursuit", "label": "Режим преследования", "type": "checkbox"},
                ],
            },
            {
                "number": "7",
                "title": "Атака смешения WIDS / WIPS / WDS",
                "kind": "action",
                "action": "wds_confusion",
                "icon": "bi-shuffle",
                "needs_interface": True,
                "fields": [
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                    {"name": "pursuit", "label": "Режим преследования", "type": "checkbox"},
                ],
            },
            {
                "number": "8",
                "title": "Атака флудом маяков (beacon)",
                "kind": "action",
                "action": "beacon_flood",
                "icon": "bi-broadcast-pin",
                "needs_interface": True,
                "fields": [
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                    {"name": "pursuit", "label": "Режим преследования", "type": "checkbox"},
                ],
            },
            {
                "number": "9",
                "title": "DoS атака деаутентификации",
                "kind": "action",
                "action": "auth_dos",
                "icon": "bi-shield-x",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "pursuit", "label": "Режим преследования", "type": "checkbox"},
                ],
            },
            {
                "number": "10",
                "title": "Атака отключения Michael (TKIP)",
                "kind": "action",
                "action": "michael_shutdown",
                "icon": "bi-exclamation-octagon",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "pursuit", "label": "Режим преследования", "type": "checkbox"},
                ],
            },
        ],
    },
    "handshake_tools": {
        "slug": "handshake_tools",
        "title": "Меню инструментов для работы с рукопожатием",
        "parent_href": "main_menu_page",
        "items": [
            *_COMMON_INTERFACE_ITEMS,
            {
                "number": "4",
                "title": "Поиск целей WPA (режим монитора)",
                "kind": "action",
                "action": "scan_wpa_targets",
                "icon": "bi-radar",
                "needs_interface": True,
                "fields": [{"name": "seconds", "label": "Длительность (сек)", "type": "number", "default": "30"}],
            },
            {
                "number": "5",
                "title": "Захват рукопожатия",
                "kind": "action",
                "action": "capture_handshake",
                "icon": "bi-file-lock2",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text"},
                    {"name": "essid", "label": "ESSID", "type": "text"},
                    {"name": "channel", "label": "Канал", "type": "number"},
                ],
            },
            {
                "number": "6",
                "title": "Очистка/оптимизация файла рукопожатия",
                "kind": "action",
                "action": "clean_handshake",
                "icon": "bi-brush",
                "fields": [{"name": "file", "label": "Путь к .cap файлу", "type": "text", "required": True}],
            },
        ],
    },
    "decrypt": {
        "slug": "decrypt",
        "title": "Меню офлайн расшифровки WPA/WPA2",
        "parent_href": "main_menu_page",
        "items": [
            {"number": "0", "title": "Вернуться в главное меню", "kind": "link", "href": "main_menu_page", "icon": "bi-arrow-left"},
            {"number": "1", "title": "Personal", "kind": "link", "href": "menu_decrypt_personal", "icon": "bi-person"},
            {"number": "2", "title": "Enterprise", "kind": "link", "href": "menu_decrypt_enterprise", "icon": "bi-building"},
        ],
    },
    "decrypt_personal": {
        "slug": "decrypt_personal",
        "title": "Personal — офлайн расшифровка",
        "parent_href": "menu_decrypt",
        "items": [
            {"number": "0", "title": "Вернуться в меню расшифровки", "kind": "link", "href": "menu_decrypt", "icon": "bi-arrow-left"},
            {
                "number": "1",
                "title": "(aircrack) Атака по словарю",
                "kind": "action",
                "action": "aircrack_dictionary",
                "icon": "bi-key",
                "fields": [
                    {"name": "capture_file", "label": "Файл захвата (.cap)", "type": "text", "required": True},
                    {"name": "dictionary", "label": "Словарь", "type": "text", "required": True},
                ],
            },
            {
                "number": "2",
                "title": "(aircrack + crunch) Грубая сила",
                "kind": "action",
                "action": "aircrack_bruteforce",
                "icon": "bi-cpu",
                "fields": [{"name": "capture_file", "label": "Файл захвата (.cap)", "type": "text", "required": True}],
            },
            {
                "number": "3",
                "title": "(hashcat) Атака по словарю",
                "kind": "action",
                "action": "hashcat_dictionary_personal",
                "icon": "bi-gpu-card",
                "fields": [
                    {"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True},
                    {"name": "dictionary", "label": "Словарь", "type": "text", "required": True},
                ],
            },
            {
                "number": "4",
                "title": "(hashcat) Полный перебор",
                "kind": "action",
                "action": "hashcat_bruteforce_personal",
                "icon": "bi-gpu-card",
                "fields": [{"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True}],
            },
            {
                "number": "5",
                "title": "(hashcat) Атака на основе правил",
                "kind": "action",
                "action": "hashcat_rulebased_personal",
                "icon": "bi-gpu-card",
                "fields": [
                    {"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True},
                    {"name": "dictionary", "label": "Словарь", "type": "text", "required": True},
                    {"name": "rules", "label": "Файл правил", "type": "text", "required": True},
                ],
            },
        ],
    },
    "decrypt_enterprise": {
        "slug": "decrypt_enterprise",
        "title": "Enterprise — офлайн расшифровка",
        "parent_href": "menu_decrypt",
        "items": [
            {"number": "0", "title": "Вернуться в меню расшифровки", "kind": "link", "href": "menu_decrypt", "icon": "bi-arrow-left"},
            {
                "number": "1",
                "title": "(john) Атака по словарю",
                "kind": "action",
                "action": "john_dictionary",
                "icon": "bi-key",
                "fields": [
                    {"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True},
                    {"name": "dictionary", "label": "Словарь", "type": "text", "required": True},
                ],
            },
            {
                "number": "2",
                "title": "(john + crunch) Грубая сила",
                "kind": "action",
                "action": "john_bruteforce",
                "icon": "bi-cpu",
                "fields": [{"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True}],
            },
            {
                "number": "3",
                "title": "(hashcat) Атака по словарю",
                "kind": "action",
                "action": "hashcat_dictionary_enterprise",
                "icon": "bi-gpu-card",
                "fields": [
                    {"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True},
                    {"name": "dictionary", "label": "Словарь", "type": "text", "required": True},
                ],
            },
            {
                "number": "4",
                "title": "(hashcat) Полный перебор",
                "kind": "action",
                "action": "hashcat_bruteforce_enterprise",
                "icon": "bi-gpu-card",
                "fields": [{"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True}],
            },
            {
                "number": "5",
                "title": "(hashcat) Атака на основе правил",
                "kind": "action",
                "action": "hashcat_rulebased_enterprise",
                "icon": "bi-gpu-card",
                "fields": [
                    {"name": "capture_file", "label": "Файл захвата", "type": "text", "required": True},
                    {"name": "dictionary", "label": "Словарь", "type": "text", "required": True},
                    {"name": "rules", "label": "Файл правил", "type": "text", "required": True},
                ],
            },
            {
                "number": "6",
                "title": "(asleap) Атака по словарю на вызов/ответ",
                "kind": "action",
                "action": "asleap_dictionary",
                "icon": "bi-shield-lock",
                "fields": [
                    {"name": "challenge", "label": "Challenge", "type": "text", "required": True},
                    {"name": "response", "label": "Response", "type": "text", "required": True},
                    {"name": "dictionary", "label": "Словарь", "type": "text", "required": True},
                ],
            },
        ],
    },
    "evil_twin": {
        "slug": "evil_twin",
        "title": "Меню атак Злой Двойник",
        "parent_href": "main_menu_page",
        "items": [
            *_COMMON_INTERFACE_ITEMS,
            _SCAN_ITEM,
            {
                "number": "5",
                "title": "Злой Двойник, только ТД",
                "kind": "action",
                "action": "et_onlyap",
                "icon": "bi-router",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID цели", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "6",
                "title": "Злой Двойник ТД со сниффингом",
                "kind": "action",
                "action": "et_sniffing",
                "icon": "bi-eye",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "7",
                "title": "Злой Двойник + sslstrip",
                "kind": "action",
                "action": "et_sniffing_sslstrip",
                "icon": "bi-incognito",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "8",
                "title": "Злой Двойник + bettercap/BeEF",
                "kind": "action",
                "action": "et_sniffing_sslstrip2",
                "icon": "bi-bug",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "9",
                "title": "Злой Двойник с перехватывающим порталом",
                "kind": "action",
                "action": "et_captive_portal",
                "icon": "bi-window",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
        ],
    },
    "wps_attacks": {
        "slug": "wps_attacks",
        "title": "Меню атак на WPS",
        "parent_href": "main_menu_page",
        "items": [
            *_COMMON_INTERFACE_ITEMS,
            {
                "number": "4",
                "title": "Поиск целей WPS",
                "kind": "action",
                "action": "scan_wps_targets",
                "icon": "bi-radar",
                "needs_interface": True,
                "fields": [{"name": "seconds", "label": "Длительность (сек)", "type": "number", "default": "30"}],
            },
            {
                "number": "5",
                "title": "(bully) Подключение с известным PIN",
                "kind": "action",
                "action": "wps_custompin_bully",
                "icon": "bi-upc",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                    {"name": "pin", "label": "PIN", "type": "text", "required": True},
                ],
            },
            {
                "number": "6",
                "title": "(reaver) Подключение с известным PIN",
                "kind": "action",
                "action": "wps_custompin_reaver",
                "icon": "bi-upc-scan",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                    {"name": "pin", "label": "PIN", "type": "text", "required": True},
                ],
            },
            {
                "number": "7",
                "title": "(bully) Pixie Dust",
                "kind": "action",
                "action": "wps_pixiedust_bully",
                "icon": "bi-stars",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "8",
                "title": "(reaver) Pixie Dust",
                "kind": "action",
                "action": "wps_pixiedust_reaver",
                "icon": "bi-stars",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "9",
                "title": "(bully) Полный перебор PIN",
                "kind": "action",
                "action": "wps_bruteforce_bully",
                "icon": "bi-arrow-repeat",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "10",
                "title": "(reaver) Полный перебор PIN",
                "kind": "action",
                "action": "wps_bruteforce_reaver",
                "icon": "bi-arrow-repeat",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "11",
                "title": "(bully) Атака по базе PIN",
                "kind": "action",
                "action": "wps_pindb_bully",
                "icon": "bi-database",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "12",
                "title": "(reaver) Атака по базе PIN",
                "kind": "action",
                "action": "wps_pindb_reaver",
                "icon": "bi-database",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "13",
                "title": "(reaver) Null PIN",
                "kind": "action",
                "action": "wps_nullpin_reaver",
                "icon": "bi-slash-circle",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
        ],
    },
    "wep_attacks": {
        "slug": "wep_attacks",
        "title": "Меню атак на WEP",
        "parent_href": "main_menu_page",
        "items": [
            *_COMMON_INTERFACE_ITEMS,
            {
                "number": "4",
                "title": "Поиск целей WEP",
                "kind": "action",
                "action": "scan_wep_targets",
                "icon": "bi-radar",
                "needs_interface": True,
                "fields": [{"name": "seconds", "label": "Длительность (сек)", "type": "number", "default": "30"}],
            },
            {
                "number": "5",
                "title": "Атака на WEP «Все-в-Одном»",
                "kind": "action",
                "action": "wep_allinone",
                "icon": "bi-unlock",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
        ],
    },
    "enterprise_attacks": {
        "slug": "enterprise_attacks",
        "title": "Меню Enterprise атак",
        "parent_href": "main_menu_page",
        "items": [
            *_COMMON_INTERFACE_ITEMS,
            {
                "number": "4",
                "title": "Поиск целей WPA Enterprise",
                "kind": "action",
                "action": "scan_enterprise_targets",
                "icon": "bi-radar",
                "needs_interface": True,
                "fields": [{"name": "seconds", "label": "Длительность (сек)", "type": "number", "default": "30"}],
            },
            {
                "number": "5",
                "title": "Создать пользовательские сертификаты",
                "kind": "action",
                "action": "enterprise_create_certs",
                "icon": "bi-file-earmark-lock",
            },
            {
                "number": "6",
                "title": "Smooth режим Enterprise Evil Twin",
                "kind": "action",
                "action": "enterprise_smooth",
                "icon": "bi-building-lock",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
            {
                "number": "7",
                "title": "Noisy режим Enterprise Evil Twin",
                "kind": "action",
                "action": "enterprise_noisy",
                "icon": "bi-building-exclamation",
                "needs_interface": True,
                "fields": [
                    {"name": "bssid", "label": "BSSID", "type": "text", "required": True},
                    {"name": "essid", "label": "ESSID", "type": "text", "required": True},
                    {"name": "channel", "label": "Канал", "type": "number", "required": True},
                ],
            },
        ],
    },
}

MAIN_MENU_LINKS: dict[str, str] = {
    "2": "menu_monitor",
    "3": "menu_managed",
    "4": "menu_dos_attacks",
    "5": "menu_handshake_tools",
    "6": "menu_decrypt",
    "7": "menu_evil_twin",
    "8": "menu_wps_attacks",
    "9": "menu_wep_attacks",
    "10": "menu_enterprise_attacks",
}


def get_menu(slug: str) -> dict[str, Any] | None:
    return MENUS.get(slug)


def list_menu_slugs() -> list[str]:
    return sorted(MENUS.keys())
